# Generated by Django 5.2 on 2025-04-14 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('Aventureiros', 'Aventureiros'), ('Desbravadores', 'Desbravadores')], max_length=20)),
                ('tipo_negocio', models.CharField(choices=[('Venda', 'Venda'), ('Troca', 'Troca')], max_length=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
